-- NOTE: This file is generated by build_app_uninstall.sql.
drop table stat_calc_type cascade constraints purge;
drop_table('stat');
drop_table('stat_property');
drop table stat_bucket cascade constraints purge;
drop table stat_in cascade constraints purge;
drop table stat_archive cascade constraints purge;
drop sequence seq_stat_work_id;
drop table stat_work cascade constraints purge;
drop table stat_avg_val_hist_ref cascade constraints purge;
drop table stat_percentiles_ref cascade constraints purge;
drop_table('stat_detail');
drop package statzilla;
exec drop_scheduler_job('statzilla_process_buckets');
exec drop_scheduler_job('statzilla_get_oracle_metrics');
