echo "-- NOTE: This file is generated by build_app_uninstall.sql." > ./arcsql_uninstall.sql

grep "^@" arcsql_install.sql | sed 's/^@/\.\//' | \
while read file_name; do 
   echo "grep \"^\-\- uninstall:\" \"${file_name}\""
   grep "^\-\- uninstall:" "${file_name}" | cut -d" " -f3- >> ./arcsql_uninstall.sql
done 
