
begin
   if 1=1 then
      drop_table('stripe_data');
      drop_table('stripe_customer');
      drop_table('stripe_subscription');
      drop_table('stripe_product');
      drop_table('stripe_subscription_product');
   end if;
end;
/

-- uninstall: exec drop_table('stripe_data');
begin
   if not does_table_exist('stripe_data') then 
      execute_sql('
      create table stripe_data (
      request_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      event_type varchar2(120),
      event_id varchar2(120),
      created timestamp default systimestamp not null,
      updated timestamp default systimestamp not null,
      event_request_body clob,
      -- ToDo: Convert above to json which requires fixing k2_json procs to handle json instead of clob.
      parse_status varchar2(12) default ''new'')', false);
   end if;
   add_primary_key('stripe_data', 'request_id');
   if not does_index_exist('stripe_data_1') then 
      execute_sql('create index stripe_data_1 on stripe_data (parse_status)', false);
   end if;
end;
/

-- uninstall: exec drop_table('stripe_customer');
begin 
   if not does_table_exist('stripe_customer') then 
      execute_sql('
      create table stripe_customer (
      customer_id varchar2(256) not null,
      email varchar2(256) not null,
      user_id number default null,
      created timestamp default systimestamp not null,
      updated timestamp default systimestamp not null)');
   end if;
   add_primary_key('stripe_customer', 'customer_id');
   if not does_constraint_exist('fk_stripe_customer_user_id') then 
      execute_sql('
      alter table stripe_customer add constraint fk_stripe_customer_user_id
      foreign key (user_id) references saas_auth (user_id) on delete cascade');
   end if;
end;
/

-- uninstall: exec drop_table('stripe_subscription');
begin 
   if not does_table_exist('stripe_subscription') then 
      execute_sql('
      create table stripe_subscription (
      subscription_id varchar2(256) not null,
      customer_id varchar2(256) not null,
      status varchar2(256) not null,
      livemode number default null,
      cancel_at number default null,
      start_date number default null,
      current_period_start number default null,
      current_period_end number default null,
      trial_start number default null,
      trial_end number default null,
      created timestamp default systimestamp not null,
      updated timestamp default systimestamp not null)');
   end if;
   add_primary_key('stripe_subscription', 'subscription_id');
   if not does_constraint_exist('fk_stripe_subscription_customer_id') then 
      execute_sql('
      alter table stripe_subscription add constraint fk_stripe_subscription_customer_id
      foreign key (customer_id) references stripe_customer (customer_id) on delete cascade');
   end if;
end;
/

-- uninstall: exec drop_table('stripe_product');
begin 
   if not does_table_exist('stripe_product') then 
      execute_sql('
      create table stripe_product (
      product_id varchar2(256) not null,
      name varchar2(256) not null,
      active number default null,
      created timestamp default systimestamp not null,
      updated timestamp default systimestamp not null)');
   end if;
   add_primary_key('stripe_product', 'product_id');
end;
/

-- uninstall: exec drop_table('stripe_subscription_product');
begin 
   if not does_table_exist('stripe_subscription_product') then 
      execute_sql('
      create table stripe_subscription_product (
      subscription_id varchar2(256) not null,
      product_id varchar2(256) not null,
      created timestamp default systimestamp not null,
      updated timestamp default systimestamp not null)');
   end if;
end;
/
