

exec drop_table('stripe_webhooks');
-- uninstall: exec drop_table('stripe_webhooks');
begin
   if not does_table_exist('stripe_webhooks') then 
      execute_sql('
      create table stripe_webhooks (
      request_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      event_id varchar2(100),
      event_object varchar2(100),
      event_api_version varchar2(100),
      event_created number,
      event_data clob,
      event_livemode varchar2(100),
      event_pending_webhooks number,
      event_request clob,
      event_type varchar2(100),
      event_request_body clob)', false);
   end if;
end;
/

