
begin
   if app_dev.drop_tables then
      drop_table('stripe_data');
   end if;
end;
/

-- uninstall: exec drop_table('stripe_data');
begin
   if not does_table_exist('stripe_data') then 
      execute_sql('
      create table stripe_data (
      request_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      event_type varchar2(120),
      event_id varchar2(120),
      email varchar2(120),
      name varchar2(120),
      status varchar2(120),
      subscription_id varchar2(120),
      livemode number,
      payment_link varchar2(120),
      customer_id varchar2(120),
      invoice_id varchar2(120),
      -- Populated on the invoice line.
      product_id varchar2(120),
      created timestamp default systimestamp not null,
      updated timestamp default systimestamp not null,
      event_request_body clob,
      -- ToDo: Convert above to json which requires fixing k2_json procs to handle json instead of clob.
      parse_status varchar2(12) default ''new'')', false);
   end if;
   add_pk_constraint('stripe_data', 'request_id');
   if not does_index_exist('stripe_data_1') then 
      execute_sql('create index stripe_data_1 on stripe_data (parse_status)', false);
   end if;
end;
/

