
-- uninstall: drop package saas_auth_config;
create or replace package saas_auth_config as 

   -- Determines if http or https for links generated by the auth service.
   saas_auth_protocol varchar2(12) := 'https';

   -- The domain used in links generated by the auth service.
   saas_auth_domain varchar2(120) := 'k2.maxapex.net';

   -- From address to use in generated emails.
   saas_auth_from_address varchar2(120) := 'donotreply@notmydomain.com';

   saas_auth_salt varchar2(120) := 'menTROuvrOntANcHEATHeRenARiNeOpsychEstaXEmPlasaTeROTErIaTeRickPINErkyOLetidaNGLInGingHtcaNdOsIDEMbE';
   saas_auth_test_pass varchar2(120) := 'ION_ZAR_AG_IN_38';

   -- Prevent users from creating account unless thier passwords start with this secret prefix.
   saas_auth_pass_prefix varchar2(120) := 'ABBA';

   -- Limits the rate of auth requests within any 10 minute window.
   -- Null to disable.
   auth_request_rate_limit number := 1000;

   -- How long is a new password token good for?
   -- Null or 0 makes the limit unlimited.
   token_good_for_minutes number := 60*24;

   -- User will not be allowed to login if email is not verified.
   -- Null to disable
   allowed_logins_before_email_verification_is_required number := 1;

   -- Enable auth notifications if your pages use them.
   flash_notifications boolean := true;

   password_reset_token_good_for_minutes number := 15;

   -- Route all emails to this address instead of using the address for the account. Used for dev/test.
   global_email_override varchar2(120) := 'donotreply@notmydomain.com';

   send_email_on_create_account boolean := true;

   -- Days user can auto login for if they select the checkbox on login form.
   -- Set to zero or null to disable and hide the checkbox.
   enable_auto_login_days number := 30;

end;
/
