-- NOTE: This file is generated by build_app_uninstall.sql.
exec drop_table('saas_auth_role');
exec drop_table('saas_auth');
exec drop_view('v_saas_auth_available_accounts');
exec drop_table('saas_auth_token');
exec drop_package('saas_auth_pkg');
exec drop_scheduler_job('saas_auth_automation_daily');
