
-- uninstall: drop package saas_auth_config;
create or replace package saas_auth_config as 

   -- Set to a default timezone to use in cases when you don't know time zone.
   default_timezone varchar2(128) := 'US/Eastern';

   -- Determines if http or https for links generated by the auth service.
   saas_auth_protocol varchar2(16) := 'https';

   -- The domain used in links generated by the auth service.
   saas_auth_domain varchar2(256) := 'xxxxxxxxxxxxxxxxxxx.adb.us-phoenix-1.oraclecloudapps.com';

   saas_auth_salt varchar2(256) := 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

   -- Prevent users from creating account unless passwords start with this secret prefix.
   saas_auth_pass_prefix varchar2(256) := '';

   -- Limits the rate of auth requests within any 10 minute window.
   -- Null to disable.
   auth_request_rate_limit number := 1000;

   -- User will not be allowed to login if email is not verified.
   -- Null to disable
   allowed_logins_before_email_verification_is_required number := 1;

   -- Enable auth notifications if your pages use them.
   flash_notifications boolean := true;

   password_reset_token_good_for_minutes number := 15;

   send_email_after_create_account boolean := true;

   -- Days user can auto login for if they select the checkbox on login form.
   -- Set to zero or null to disable and hide the checkbox.
   enable_auto_login_days number := 30;

   password_minimum_length number := 8;
   password_minimum_upper number := 1;
   password_minimum_lower number := 1;
   password_minimum_digit number := 1;

   verify_email_redirect varchar2(128) := 'home';
   verify_email_expire_minutes number := 60;
   forgot_pass_redirect varchar2(128) := 'change-pass';
   forgot_pass_expire_minutes number := 60;

end;
/
