
-- uninstall: drop package saas_auth_config;
create or replace package saas_auth_config as 

   -- Determines if http or https for links generated by the auth service.
   saas_auth_protocol varchar2(12) := 'https';

   -- The domain used in links generated by the auth service.
   saas_auth_domain varchar2(120) := 'k2.maxapex.net';

   saas_auth_salt varchar2(120) := 'menTROuvrOntANcHEATHeRenARiNeOpsychEstaXEmPlasaTeROTErIaTeRickPINErkyOLetidaNGLInGingHtcaNdOsIDEMbE';
   saas_auth_test_pass varchar2(120) := 'ION_ZAR_AG_IN_38';

   -- Prevent users from creating account unless thier passwords start with this secret prefix.
   saas_auth_pass_prefix varchar2(120) := null;

   -- Limits the rate of auth requests within any 10 minute window.
   -- Null to disable.
   auth_request_rate_limit number := 1000;

   -- How long is a new token good for?
   -- Null or 0 makes the limit unlimited.
   token_good_for_minutes number := 60*24;

   -- User will not be allowed to login if email is not verified.
   -- Null to disable
   allowed_logins_before_email_verification_is_required number := 1;

   -- Enable auth notifications if your pages use them.
   flash_notifications boolean := true;

   password_reset_token_good_for_minutes number := 15;

   send_email_after_create_account boolean := true;

   -- Days user can auto login for if they select the checkbox on login form.
   -- Set to zero or null to disable and hide the checkbox.
   enable_auto_login_days number := 30;

   -- This is the message that appears on the login page. This is optional. You can modify the page directly to over-ride this message.
   login_form_banner varchar2(200) := 'Login to access this application.';

end;
/
