
echo "-- NOTE: This file is generated by build_app_uninstall.sql." > ./app_uninstall.sql

(
grep "^@" app_install.sql | sed 's/^@/\.\//' | while read file_name; do
   grep "^\-\- uninstall:" "${file_name}" | cut -d" " -f3-
done

find . -type f | while read file_name; do 
   grep "^\-\- uninstall:" "${file_name}" | cut -d" " -f3- >> ./app_uninstall.sql
done
) >> ./app_uninstall.sql

cat ./app_uninstall.sql

