-- NOTE: This file is generated by build_app_uninstall.sql.
exec drop_package('app');
exec drop_package('app_config');
exec drop_package('app_api');
exec drop_procedure('after_create_account');
exec drop_procedure('before_delete_user');
exec drop_procedure('after_delete_user');
exec drop_procedure('on_login');
exec drop_scheduler_job('foo');
exec drop_package('app_api');
exec drop_procedure('after_create_account');
exec drop_procedure('before_delete_user');
exec drop_procedure('after_delete_user');
exec drop_procedure('on_login');
exec drop_package('app');
exec drop_package('app_config');
exec drop_scheduler_job('foo');
