
exec drop_table('access_key');
exec drop_table('access_keys');

-- uninstall: exec drop_table('access_key');

begin 
	if not does_table_exist('access_keys') then 
		execute_sql('
		create table access_keys (
		access_key_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
		access_key_key varchar2(250) not null,
		access_key varchar2(250) not null,
		is_enabled number default 1 not null,
		user_id number not null,
		created timestamp default systimestamp,
		updated timestamp default systimestamp)', false);
	end if;
	add_pk_constraint('access_keys', 'access_key_id');
	if not does_constraint_exist('access_key_fk_user_id') then
		execute_sql('alter table access_keys add constraint access_key_fk_user_id foreign key (user_id) references saas_auth (user_id) on delete cascade', false);
	end if;
	if not does_index_exist('access_key_1') then
		execute_sql('create unique index access_key_1 on access_keys (access_key_key)', false);
	end if;
end;
/
