
begin
   if 1=2 then
      drop_table('file_store');
   end if;
end;
/

-- uninstall: exec drop_table('file_store');
begin 
   if not does_table_exist('file_store') then
      execute_sql(q'<
      create table file_store (
      file_store_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      file_store_key varchar2(256) not null,
      file_name varchar2(256) not null,
      file_format varchar2(5) not null,
      file_mimetype varchar2(256) not null,
      file_blob blob default null,
      file_tags varchar2(256) default null,
      file_sql clob default null,
      created timestamp default systimestamp not null,
      updated timestamp default systimestamp not null,
      user_id number default null,
      constraint pk_file_store primary key (file_store_id),
      constraint chk_file_store_file_format check (file_format in ('CSV', 'HTML', 'PDF', 'XLSX', 'XML', 'PXML', 'JSON', 'PJSON')))>', false);
   end if;
   if not does_index_exist('file_store_1') then
      execute_sql('create unique index file_store_1 on file_store (file_store_key)', false);
   end if;
end;
/

