
begin
   if 1=2 then
      drop_table('json_store');
      drop_table('json_data');
   end if;
end;
/

-- uninstall: exec drop_table('json_store');
exec drop_index('unique_json_store_json_key');
begin
	if not does_table_exist('json_store') then 
		execute_sql('
		create table json_store (
		json_store_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
		json_key varchar2(128) not null,
		json_data json)', false);
	end if;
	add_primary_key('json_store', 'json_store_id');
	if not does_constraint_exist('check_json_store_json_data') then
		execute_sql('
		alter table json_store
			add constraint check_json_store_json_data check (json_data is json)', false);
	end if;
	if not does_index_exist('unq_json_store_json_key') then
		execute_sql('
		create unique index unq_json_store_json_key on json_store (json_key)', false);
	end if;
end;
/

-- uninstall: exec drop_table('json_data');
begin
	if not does_table_exist('json_data') then 
		execute_sql('
		create table json_data (
		json_data_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
		json_key varchar2(128) not null,
		json_path varchar2(512) not null,
		data_index number default 0 not null,
		data_type varchar2(32),
		data_size number not null,
		data_value varchar2(4000),
		data_key varchar2(128) not null)', false);
	end if;
	add_primary_key('json_data', 'json_data_id');
end;
/


