-- NOTE: This file is generated by build_app_uninstall.sql.
exec drop_package('k2_config');
exec drop_table('cookie');
exec drop_table('flash_message');
exec drop_view('user_flash_message');
exec drop_package('k2');
