
begin
   if 1=1 then
      -- Add drop_table statements here if you want in any env where 1=0 is true.
      drop_table('chatgpt_chat_completions');
      drop_table('chatgpt_images');
   end if;
end;
/


begin
	if not does_table_exist('chatgpt_chat_completions') then
		execute_sql('
		create table chatgpt_chat_completions (
		chatgpt_chat_completions_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
		chat_session_id varchar2(128), -- Identifies one or more rows as belonging to a single chat.
		role varchar(16), -- system, user or associate
		request_id varchar(128), -- Each request gets a unique id. The response will also be in this table and occurs within the same request so will have the same request id.
		response_status number, -- HTTP response code
		content clob, -- The message or the response
		created timestamp default systimestamp
		)');
	end if;
	add_primary_key('chatgpt_chat_completions', 'chatgpt_chat_completions_id');
	if not does_index_exist('chatgpt_chat_completions_1') then 
		execute_sql('create index chatgpt_chat_completions_1 on chatgpt_chat_completions (request_id)');
	end if;
	if not does_index_exist('chatgpt_chat_completions_2') then 
		execute_sql('create index chatgpt_chat_completions_2 on chatgpt_chat_completions (chat_session_id)');
	end if;
end;
/

begin
	if not does_table_exist('chatgpt_images') then 
		execute_sql('
		create table chatgpt_images (
		chatgpt_images_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
		image_session_id varchar(128), 
		request_id varchar(128),
		prompt varchar(1024),
		image_number number,
		response_status number,
		content blob,
		url varchar2(512),
		created timestamp default systimestamp
		)');
	end if;
	add_primary_key('chatgpt_images', 'chatgpt_images_id');
end;
/
